<?php
/**
 * @file
 * Custom Fivestar formatter module.
 */

/**
* Implements hook_field_formatter_info().
*/
function custom_fivestar_formatter_field_formatter_info() {
  $info = array(
    'fivestar_number_formatter' => array(
      'label' => t('Simple number'),
      'field types' => array('fivestar'),
      'description' => t('Displays rate as a simple number'),
    ),
    'fivestar_grade_formatter' => array(
      'label' => t('Grade'),
      'field types' => array('fivestar'),
      'description' => t('Displays rate as a grade. Labeled number'),
    ),
    'fivestar_range_formatter' => array(
      'label' => t('Range'),
      'field types' => array('fivestar'),
      'description' => t('Displays rate as a range'),
    ),
  );
  return $info;
}

/**
* Implements hook_field_formatter_view().
*/
function custom_fivestar_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'fivestar_number_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'custom_fivestar_number_formatter',
          '#instance_settings' => $instance['settings'],
          '#item' => $items[0],
        );
      }
      break;
    case 'fivestar_grade_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => t('Grade: @grade', array('@grade' => theme('custom_fivestar_number_formatter', array(
            'instance_settings' => $instance['settings'],
            'item' => $items[0],
          )))),
        );
      }
      break;
    case 'fivestar_range_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'custom_fivestar_range_formatter',
          '#instance_settings' => $instance['settings'],
          '#item' => $items[0],
        );
      }
      break;
  }
  return $element;
}

/**
* Implements hook_theme().
*/
function custom_fivestar_formatter_theme() {
  return array(
    'custom_fivestar_number_formatter' => array(
      'variables' => array(
        'instance_settings' => NULL,
        'item' => NULL,
      ),
      'file' => 'custom_fivestar_formatter.theme.inc',
    ),
    'custom_fivestar_range_formatter' => array(
      'variables' => array(
        'instance_settings' => NULL,
        'item' => NULL,
      ),
      'file' => 'custom_fivestar_formatter.theme.inc',
    ),
  );
}

/**
 * Helper function to get rating.
 *
 * @param array $variables
 * An associative array (taken from a theme function) containing:
 * - instance_settings: Fivestar instance settings.
 * - item: Item.
 *
 * @return float
 *   Rating.
 */
function custom_fivestar_number_get_rating($variables) {
  $item = $variables['item'];
  $instance_settings = $variables['instance_settings'];
  if (empty($item['average'])) {
    $item['average'] = 0;
  }
  // Get number of stars.
  $stars = (empty($instance_settings['stars'])) ? 5 : $instance_settings['stars'];
  $average = $item['average'];
  return round(($average/100) * $stars, 1);
}
